// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/peerly-backend/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/joshsoftware/peerly-backend/internal/repository"

	sqlx "github.com/jmoiron/sqlx"
)

// AppreciationStorer is an autogenerated mock type for the AppreciationStorer type
type AppreciationStorer struct {
	mock.Mock
}

// BeginTx provides a mock function with given fields: ctx
func (_m *AppreciationStorer) BeginTx(ctx context.Context) (repository.Transaction, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 repository.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.Transaction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateAppreciation provides a mock function with given fields: ctx, tx, appreciation
func (_m *AppreciationStorer) CreateAppreciation(ctx context.Context, tx repository.Transaction, appreciation dto.Appreciation) (repository.Appreciation, error) {
	ret := _m.Called(ctx, tx, appreciation)

	var r0 repository.Appreciation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, dto.Appreciation) (repository.Appreciation, error)); ok {
		return rf(ctx, tx, appreciation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, dto.Appreciation) repository.Appreciation); ok {
		r0 = rf(ctx, tx, appreciation)
	} else {
		r0 = ret.Get(0).(repository.Appreciation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Transaction, dto.Appreciation) error); ok {
		r1 = rf(ctx, tx, appreciation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAppreciation provides a mock function with given fields: ctx, tx, apprId
func (_m *AppreciationStorer) DeleteAppreciation(ctx context.Context, tx repository.Transaction, apprId int32) error {
	ret := _m.Called(ctx, tx, apprId)
	return ret.Error(0)
}

// GetAppreciationById provides a mock function with given fields: ctx, tx, appreciationId
func (_m *AppreciationStorer) GetAppreciationById(ctx context.Context, tx repository.Transaction, appreciationId int32) (repository.AppreciationResponse, error) {
	ret := _m.Called(ctx, tx, appreciationId)

	var r0 repository.AppreciationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int32) (repository.AppreciationResponse, error)); ok {
		return rf(ctx, tx, appreciationId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int32) repository.AppreciationResponse); ok {
		r0 = rf(ctx, tx, appreciationId)
	} else {
		r0 = ret.Get(0).(repository.AppreciationResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Transaction, int32) error); ok {
		r1 = rf(ctx, tx, appreciationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDB provides a mock function with given fields:
func (_m *AppreciationStorer) GetDB() *sqlx.DB {
	ret := _m.Called()
	if rf, ok := ret.Get(0).(func() *sqlx.DB); ok {
		return rf()
	}
	if ret.Get(0) != nil {
		return ret.Get(0).(*sqlx.DB)
	}
	return nil
}

// HandleTransaction provides a mock function with given fields: ctx, tx, isSuccess
func (_m *AppreciationStorer) HandleTransaction(ctx context.Context, tx repository.Transaction, isSuccess bool) error {
	ret := _m.Called(ctx, tx, isSuccess)
	return ret.Error(0)
}

// IsUserPresent provides a mock function with given fields: ctx, tx, userID
func (_m *AppreciationStorer) IsUserPresent(ctx context.Context, tx repository.Transaction, userID int64) (bool, error) {
	ret := _m.Called(ctx, tx, userID)
	return ret.Get(0).(bool), ret.Error(1)
}

// ListAppreciations provides a mock function with given fields: ctx, tx, filter
func (_m *AppreciationStorer) ListAppreciations(ctx context.Context, tx repository.Transaction, filter dto.AppreciationFilter) ([]repository.AppreciationResponse, repository.Pagination, error) {
	ret := _m.Called(ctx, tx, filter)
	return ret.Get(0).([]repository.AppreciationResponse), ret.Get(1).(repository.Pagination), ret.Error(2)
}

// AddRewardPointsToAppreciation provides a mock function with given fields: ctx, tx, apprID, ratingPoint
func (_m *AppreciationStorer) AddRewardPointsToAppreciation(ctx context.Context, tx repository.Transaction, apprID int64, ratingPoint int64) error {
	ret := _m.Called(ctx, tx, apprID, ratingPoint)
	return ret.Error(0)
}

// UpdateAppreciationTotalRewardsOfYesterday provides a mock function with given fields: ctx, tx, orgTimezone
func (_m *AppreciationStorer) UpdateAppreciationTotalRewardsOfYesterday(ctx context.Context, tx repository.Transaction, orgTimezone string) (bool, error) {
	ret := _m.Called(ctx, tx, orgTimezone)
	return ret.Get(0).(bool), ret.Error(1)
}

// UpdateUserBadgesBasedOnTotalRewards provides a mock function with given fields: ctx, tx
func (_m *AppreciationStorer) UpdateUserBadgesBasedOnTotalRewards(ctx context.Context, tx repository.Transaction) ([]repository.UserBadgeDetails, error) {
	ret := _m.Called(ctx, tx)
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction) ([]repository.UserBadgeDetails, error)); ok {
		return rf(ctx, tx)
	}
	var r0 []repository.UserBadgeDetails
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]repository.UserBadgeDetails)
	}
	return r0, ret.Error(1)
}

// InitiateQueryExecutor provides a mock function with given fields: tx
func (_m *AppreciationStorer) InitiateQueryExecutor(tx repository.Transaction) sqlx.Ext {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for InitiateQueryExecutor")
	}

	var r0 sqlx.Ext
	if rf, ok := ret.Get(0).(func(repository.Transaction) sqlx.Ext); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlx.Ext)
		}
	}

	return r0
}

func NewAppreciationStorer(t interface{}) *AppreciationStorer {
	mock := &AppreciationStorer{}
	return mock
}
