// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/peerly-backend/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/joshsoftware/peerly-backend/internal/repository"
)

// OrganizationStorer is an autogenerated mock type for the OrganizationStorer type
type OrganizationStorer struct {
	mock.Mock
}

// CreateOrganizationConfig provides a mock function with given fields: ctx, org
func (_m *OrganizationStorer) CreateOrganizationConfig(ctx context.Context, org dto.OrganizationConfig) (repository.OrganizationConfig, error) {
	ret := _m.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizationConfig")
	}

	var r0 repository.OrganizationConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.OrganizationConfig) (repository.OrganizationConfig, error)); ok {
		return rf(ctx, org)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.OrganizationConfig) repository.OrganizationConfig); ok {
		r0 = rf(ctx, org)
	} else {
		r0 = ret.Get(0).(repository.OrganizationConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.OrganizationConfig) error); ok {
		r1 = rf(ctx, org)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationConfig provides a mock function with given fields: ctx
func (_m *OrganizationStorer) GetOrganizationConfig(ctx context.Context) (repository.OrganizationConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationConfig")
	}

	var r0 repository.OrganizationConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.OrganizationConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.OrganizationConfig); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(repository.OrganizationConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrganizationCofig provides a mock function with given fields: ctx, reqOrganization
func (_m *OrganizationStorer) UpdateOrganizationCofig(ctx context.Context, reqOrganization dto.OrganizationConfig) (repository.OrganizationConfig, error) {
	ret := _m.Called(ctx, reqOrganization)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganizationCofig")
	}

	var r0 repository.OrganizationConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.OrganizationConfig) (repository.OrganizationConfig, error)); ok {
		return rf(ctx, reqOrganization)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.OrganizationConfig) repository.OrganizationConfig); ok {
		r0 = rf(ctx, reqOrganization)
	} else {
		r0 = ret.Get(0).(repository.OrganizationConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.OrganizationConfig) error); ok {
		r1 = rf(ctx, reqOrganization)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrganizationStorer creates a new instance of OrganizationStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationStorer {
	mock := &OrganizationStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
