// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import dto "github.com/joshsoftware/peerly-backend/internal/pkg/dto"
import mock "github.com/stretchr/testify/mock"

// ReportAppreciationStorer is an autogenerated mock type for the ReportAppreciationStorer type
type ReportAppreciationStorer struct {
	mock.Mock
}

// CheckAppreciation provides a mock function with given fields: ctx, reqData
func (_m *ReportAppreciationStorer) CheckAppreciation(ctx context.Context, reqData dto.ReportAppreciationReq) (bool, error) {
	ret := _m.Called(ctx, reqData)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportAppreciationReq) bool); ok {
		r0 = rf(ctx, reqData)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ReportAppreciationReq) error); ok {
		r1 = rf(ctx, reqData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckDuplicateReport provides a mock function with given fields: ctx, reqData
func (_m *ReportAppreciationStorer) CheckDuplicateReport(ctx context.Context, reqData dto.ReportAppreciationReq) (bool, error) {
	ret := _m.Called(ctx, reqData)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportAppreciationReq) bool); ok {
		r0 = rf(ctx, reqData)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ReportAppreciationReq) error); ok {
		r1 = rf(ctx, reqData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSenderAndReceiver provides a mock function with given fields: ctx, reqData
func (_m *ReportAppreciationStorer) GetSenderAndReceiver(ctx context.Context, reqData dto.ReportAppreciationReq) (dto.GetSenderAndReceiverResp, error) {
	ret := _m.Called(ctx, reqData)

	var r0 dto.GetSenderAndReceiverResp
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportAppreciationReq) dto.GetSenderAndReceiverResp); ok {
		r0 = rf(ctx, reqData)
	} else {
		r0 = ret.Get(0).(dto.GetSenderAndReceiverResp)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ReportAppreciationReq) error); ok {
		r1 = rf(ctx, reqData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportAppreciation provides a mock function with given fields: ctx, reportReq
func (_m *ReportAppreciationStorer) ReportAppreciation(ctx context.Context, reportReq dto.ReportAppreciationReq) (dto.ReportAppricaitionResp, error) {
	ret := _m.Called(ctx, reportReq)

	var r0 dto.ReportAppricaitionResp
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportAppreciationReq) dto.ReportAppricaitionResp); ok {
		r0 = rf(ctx, reportReq)
	} else {
		r0 = ret.Get(0).(dto.ReportAppricaitionResp)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ReportAppreciationReq) error); ok {
		r1 = rf(ctx, reportReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func NewReportAppreciationStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportAppreciationStorer {
	mock := &ReportAppreciationStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
