// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/peerly-backend/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/joshsoftware/peerly-backend/internal/repository"

	sqlx "github.com/jmoiron/sqlx"
)

// RewardStorer is an autogenerated mock type for the RewardStorer type
type RewardStorer struct {
	mock.Mock
}

// BeginTx provides a mock function with given fields: ctx
func (_m *RewardStorer) BeginTx(ctx context.Context) (repository.Transaction, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 repository.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.Transaction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeduceRewardQuotaOfUser provides a mock function with given fields: ctx, tx, userId, points
func (_m *RewardStorer) DeduceRewardQuotaOfUser(ctx context.Context, tx repository.Transaction, userId int64, points int) (bool, error) {
	ret := _m.Called(ctx, tx, userId, points)

	if len(ret) == 0 {
		panic("no return value specified for DeduceRewardQuotaOfUser")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64, int) (bool, error)); ok {
		return rf(ctx, tx, userId, points)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64, int) bool); ok {
		r0 = rf(ctx, tx, userId, points)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Transaction, int64, int) error); ok {
		r1 = rf(ctx, tx, userId, points)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GiveReward provides a mock function with given fields: ctx, tx, reward
func (_m *RewardStorer) GiveReward(ctx context.Context, tx repository.Transaction, reward dto.Reward) (repository.Reward, error) {
	ret := _m.Called(ctx, tx, reward)

	if len(ret) == 0 {
		panic("no return value specified for GiveReward")
	}

	var r0 repository.Reward
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, dto.Reward) (repository.Reward, error)); ok {
		return rf(ctx, tx, reward)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, dto.Reward) repository.Reward); ok {
		r0 = rf(ctx, tx, reward)
	} else {
		r0 = ret.Get(0).(repository.Reward)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Transaction, dto.Reward) error); ok {
		r1 = rf(ctx, tx, reward)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleTransaction provides a mock function with given fields: ctx, tx, isSuccess
func (_m *RewardStorer) HandleTransaction(ctx context.Context, tx repository.Transaction, isSuccess bool) error {
	ret := _m.Called(ctx, tx, isSuccess)

	if len(ret) == 0 {
		panic("no return value specified for HandleTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, bool) error); ok {
		r0 = rf(ctx, tx, isSuccess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitiateQueryExecutor provides a mock function with given fields: tx
func (_m *RewardStorer) InitiateQueryExecutor(tx repository.Transaction) sqlx.Ext {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for InitiateQueryExecutor")
	}

	var r0 sqlx.Ext
	if rf, ok := ret.Get(0).(func(repository.Transaction) sqlx.Ext); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlx.Ext)
		}
	}

	return r0
}

// IsUserRewardForAppreciationPresent provides a mock function with given fields: ctx, tx, apprId, senderId
func (_m *RewardStorer) IsUserRewardForAppreciationPresent(ctx context.Context, tx repository.Transaction, apprId int64, senderId int64) (bool, error) {
	ret := _m.Called(ctx, tx, apprId, senderId)

	if len(ret) == 0 {
		panic("no return value specified for IsUserRewardForAppreciationPresent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64, int64) (bool, error)); ok {
		return rf(ctx, tx, apprId, senderId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64, int64) bool); ok {
		r0 = rf(ctx, tx, apprId, senderId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Transaction, int64, int64) error); ok {
		r1 = rf(ctx, tx, apprId, senderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserHasRewardQuota provides a mock function with given fields: ctx, tx, userID, points
func (_m *RewardStorer) UserHasRewardQuota(ctx context.Context, tx repository.Transaction, userID int64, points int64) (bool, error) {
	ret := _m.Called(ctx, tx, userID, points)

	if len(ret) == 0 {
		panic("no return value specified for UserHasRewardQuota")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64, int64) (bool, error)); ok {
		return rf(ctx, tx, userID, points)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64, int64) bool); ok {
		r0 = rf(ctx, tx, userID, points)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Transaction, int64, int64) error); ok {
		r1 = rf(ctx, tx, userID, points)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRewardStorer creates a new instance of RewardStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRewardStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *RewardStorer {
	mock := &RewardStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
