// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/peerly-backend/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/joshsoftware/peerly-backend/internal/repository"

	sqlx "github.com/jmoiron/sqlx"
)

// UserStorer is an autogenerated mock type for the UserStorer type
type UserStorer struct {
	mock.Mock
}

// BeginTx provides a mock function with given fields: ctx
func (_m *UserStorer) BeginTx(ctx context.Context) (repository.Transaction, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 repository.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.Transaction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateNewUser provides a mock function with given fields: ctx, u
func (_m *UserStorer) CreateNewUser(ctx context.Context, u dto.RegisterUser) (dto.GetUserResp, error) {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewUser")
	}

	var r0 dto.GetUserResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterUser) (dto.GetUserResp, error)); ok {
		return rf(ctx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterUser) dto.GetUserResp); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Get(0).(dto.GetUserResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RegisterUser) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveUserList provides a mock function with given fields: ctx, tx
func (_m *UserStorer) GetActiveUserList(ctx context.Context, tx repository.Transaction) ([]repository.ActiveUser, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveUserList")
	}

	var r0 []repository.ActiveUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction) ([]repository.ActiveUser, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction) []repository.ActiveUser); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ActiveUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Transaction) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGradeByName provides a mock function with given fields: ctx, name
func (_m *UserStorer) GetGradeByName(ctx context.Context, name string) (repository.Grade, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetGradeByName")
	}

	var r0 repository.Grade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (repository.Grade, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.Grade); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(repository.Grade)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRewardMultiplier provides a mock function with given fields: ctx
func (_m *UserStorer) GetRewardMultiplier(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRewardMultiplier")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoleByName provides a mock function with given fields: ctx, name
func (_m *UserStorer) GetRoleByName(ctx context.Context, name string) (int, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleByName")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *UserStorer) GetUserByEmail(ctx context.Context, email string) (dto.GetUserResp, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 dto.GetUserResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dto.GetUserResp, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dto.GetUserResp); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(dto.GetUserResp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserList provides a mock function with given fields: ctx, reqData
func (_m *UserStorer) GetUserList(ctx context.Context, reqData dto.UserListReq) ([]dto.GetUserListResp, error) {
	ret := _m.Called(ctx, reqData)

	if len(ret) == 0 {
		panic("no return value specified for GetUserList")
	}

	var r0 []dto.GetUserListResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserListReq) ([]dto.GetUserListResp, error)); ok {
		return rf(ctx, reqData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserListReq) []dto.GetUserListResp); ok {
		r0 = rf(ctx, reqData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.GetUserListResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UserListReq) error); ok {
		r1 = rf(ctx, reqData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleTransaction provides a mock function with given fields: ctx, tx, isSuccess
func (_m *UserStorer) HandleTransaction(ctx context.Context, tx repository.Transaction, isSuccess bool) error {
	ret := _m.Called(ctx, tx, isSuccess)

	if len(ret) == 0 {
		panic("no return value specified for HandleTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, bool) error); ok {
		r0 = rf(ctx, tx, isSuccess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitiateQueryExecutor provides a mock function with given fields: tx
func (_m *UserStorer) InitiateQueryExecutor(tx repository.Transaction) sqlx.Ext {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for InitiateQueryExecutor")
	}

	var r0 sqlx.Ext
	if rf, ok := ret.Get(0).(func(repository.Transaction) sqlx.Ext); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlx.Ext)
		}
	}

	return r0
}

// SyncData provides a mock function with given fields: ctx, updateData
func (_m *UserStorer) SyncData(ctx context.Context, updateData dto.UpdateUserData) error {
	ret := _m.Called(ctx, updateData)

	if len(ret) == 0 {
		panic("no return value specified for SyncData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateUserData) error); ok {
		r0 = rf(ctx, updateData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRewardQuota provides a mock function with given fields: ctx, tx
func (_m *UserStorer) UpdateRewardQuota(ctx context.Context, tx repository.Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRewardQuota")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserStorer creates a new instance of UserStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserStorer {
	mock := &UserStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
