// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	email "github.com/joshsoftware/peerly-backend/internal/app/email"

	mock "github.com/stretchr/testify/mock"
)

// MailService is an autogenerated mock type for the MailService type
type MailService struct {
	mock.Mock
}

// SendMail provides a mock function with given fields: mailReq
func (_m *MailService) SendMail(mailReq *email.Mail) error {
	ret := _m.Called(mailReq)

	if len(ret) == 0 {
		panic("no return value specified for SendMail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*email.Mail) error); ok {
		r0 = rf(mailReq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMailService creates a new instance of MailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailService {
	mock := &MailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
