// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/peerly-backend/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/joshsoftware/peerly-backend/internal/repository"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateAppreciation provides a mock function with given fields: ctx, _a1
func (_m *Service) CreateAppreciation(ctx context.Context, _a1 dto.Appreciation) (dto.Appreciation, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppreciation")
	}

	var r0 dto.Appreciation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.Appreciation) (dto.Appreciation, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.Appreciation) dto.Appreciation); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(dto.Appreciation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.Appreciation) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAppreciation provides a mock function with given fields: ctx, apprId
func (_m *Service) DeleteAppreciation(ctx context.Context, apprId int32) error {
	ret := _m.Called(ctx, apprId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAppreciation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, apprId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAppreciationById provides a mock function with given fields: ctx, appreciationId
func (_m *Service) GetAppreciationById(ctx context.Context, appreciationId int32) (dto.AppreciationResponse, error) {
	ret := _m.Called(ctx, appreciationId)

	if len(ret) == 0 {
		panic("no return value specified for GetAppreciationById")
	}

	var r0 dto.AppreciationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (dto.AppreciationResponse, error)); ok {
		return rf(ctx, appreciationId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) dto.AppreciationResponse); ok {
		r0 = rf(ctx, appreciationId)
	} else {
		r0 = ret.Get(0).(dto.AppreciationResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, appreciationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAppreciations provides a mock function with given fields: ctx, filter
func (_m *Service) ListAppreciations(ctx context.Context, filter dto.AppreciationFilter) (dto.ListAppreciationsResponse, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListAppreciations")
	}

	var r0 dto.ListAppreciationsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.AppreciationFilter) (dto.ListAppreciationsResponse, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.AppreciationFilter) dto.ListAppreciationsResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(dto.ListAppreciationsResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.AppreciationFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAppreciation provides a mock function with given fields: ctx
func (_m *Service) UpdateAppreciation(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAppreciation")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// sendAppreciationNotificationToAll provides a mock function with given fields: ctx, appr
func (_m *Service) sendAppreciationNotificationToAll(ctx context.Context, appr repository.AppreciationResponse) {
	_m.Called(ctx, appr)
}

// sendAppreciationNotificationToReceiver provides a mock function with given fields: ctx, appr
func (_m *Service) sendAppreciationNotificationToReceiver(ctx context.Context, appr repository.AppreciationResponse) {
	_m.Called(ctx, appr)
}

// sendEmailForBadgeAllocation provides a mock function with given fields: userBadgeDetails
func (_m *Service) sendEmailForBadgeAllocation(userBadgeDetails []repository.UserBadgeDetails) {
	_m.Called(userBadgeDetails)
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
