// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/joshsoftware/peerly-backend/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GiveReward provides a mock function with given fields: ctx, rewardReq
func (_m *Service) GiveReward(ctx context.Context, rewardReq dto.Reward) (dto.Reward, error) {
	ret := _m.Called(ctx, rewardReq)

	if len(ret) == 0 {
		panic("no return value specified for GiveReward")
	}

	var r0 dto.Reward
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.Reward) (dto.Reward, error)); ok {
		return rf(ctx, rewardReq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.Reward) dto.Reward); ok {
		r0 = rf(ctx, rewardReq)
	} else {
		r0 = ret.Get(0).(dto.Reward)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.Reward) error); ok {
		r1 = rf(ctx, rewardReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
